name: Deploy zion to DigitalOcean

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh root@46.101.122.80 "cd /path/to/your/app && git pull origin main && ./deploy.sh"  # Modify this line
