name: Deploy to DigitalOcean

on:
  push:
    branches: -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to DO
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          username: ${{ secrets.DO_USERNAME }}
          script: |
            cd node-apps
            git pull origin main
            npm install
            pm2 restart app
